// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkUizzVXAI7SCJtrG1ezjTYBnVPw-wEGs',
    appId: '1:285852322280:web:6840d60824f53ea3a17c5d',
    messagingSenderId: '285852322280',
    projectId: 'diamondvault-e6fb3',
    authDomain: 'diamondvault-e6fb3.firebaseapp.com',
    storageBucket: 'diamondvault-e6fb3.firebasestorage.app',
    measurementId: 'G-3JZDP8YBQJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRa1fTeEHyF614RI4QSyxkoJw4Se_DRVs',
    appId: '1:285852322280:android:bd85b1fad077b647a17c5d',
    messagingSenderId: '285852322280',
    projectId: 'diamondvault-e6fb3',
    storageBucket: 'diamondvault-e6fb3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFade62f6VB-P0-cZX6VLQt_AniiGvJoo',
    appId: '1:285852322280:ios:0abbfd35730cca3ba17c5d',
    messagingSenderId: '285852322280',
    projectId: 'diamondvault-e6fb3',
    storageBucket: 'diamondvault-e6fb3.firebasestorage.app',
    iosBundleId: 'com.example.diamondVault',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFade62f6VB-P0-cZX6VLQt_AniiGvJoo',
    appId: '1:285852322280:ios:0abbfd35730cca3ba17c5d',
    messagingSenderId: '285852322280',
    projectId: 'diamondvault-e6fb3',
    storageBucket: 'diamondvault-e6fb3.firebasestorage.app',
    iosBundleId: 'com.example.diamondVault',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkUizzVXAI7SCJtrG1ezjTYBnVPw-wEGs',
    appId: '1:285852322280:web:0efae49deb48941ea17c5d',
    messagingSenderId: '285852322280',
    projectId: 'diamondvault-e6fb3',
    authDomain: 'diamondvault-e6fb3.firebaseapp.com',
    storageBucket: 'diamondvault-e6fb3.firebasestorage.app',
    measurementId: 'G-STR8EXT0DW',
  );
}
